"""empty message

Revision ID: 3fedd8d188cd
Revises: 9effd8c7caf2
Create Date: 2024-06-06 14:46:19.454541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fedd8d188cd'
down_revision = '9effd8c7caf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True,server_default=sa.func.current_date()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
